image: node:12.2.0-alpine

stages:
#    - lint
#    - test
    - build
build Job:
    stage: build
    tags: 
        - Jelastic
    script:
        - echo "Building deploy package"
        - npm install
        - npm install react-scripts@3.4.1 -g
        - npm run build
        - echo "Build successful"
#Test job:
#    stage: test
#    script:
#        - echo "Testing in progress" 
#        - npm install
#        - npm install react-scripts@3.4.1 -g
#        - npm test -- --coverage

#Linting job:
#    stage: lint
#    script:
#        - echo "Linting in progress" 
#        - npm install
#        - npm install react-scripts@3.4.1 -g
#        - npm run lint




#image: node:12.12.0

#variables:
#  API_KEY: 6e0fcb35-8bb4-0e5f-ef86-7a31fe3b044e

#stages:
#  - test

#run_scan:
#  stage: test
#  script:
#   - npm install
#   - npm install -g license-checker
#   - curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz && tar -C /usr/local/bin -xzf /tmp/cd-latest-linux-x64.tar.gz && chmod +x /usr/local/bin/cdefense
#   - cdefense scan --lang=node --project-name="Sppp Cicd Sample" --api-key=$API_KEY --path=$PWD
#   - echo $?



#run_scan:
#  stage: test
#  script:
#   - npm install
#   - npm install -g license-checker
#   - curl https://raw.githubusercontent.com/CloudDefenseAI/cd/master/latest/cd-latest-linux-x64.tar.gz > /tmp/cd-latest-linux-x64.tar.gz && tar -C /usr/local/bin -xzf /tmp/cd-latest-linux-x64.tar.gz && chmod +x /usr/local/bin/cdefense
#   - cdefense scan --lang=node --project-name="Sppp Cicd Sample" --api-key=$API_KEY --path=$PWD
#   - echo $?
