export const BC_NEW_WINDOW = 'BC_NEW_WINDOW';
export const BC_REMOVE_WINDOW = 'BC_REMOVE_WINDOW';
export const BC_TOGGLE_INSIGHT = 'BC_TOGGLE_INSIGHT';
export const BC_SELECT_A_BUILDING = 'BC_SELECT_A_BUILDING';
export const BC_SELECT_A_FLOOR = 'BC_SELECT_A_FLOOR';
export const BC_SHOW_WINDOW_NUMBER_MODAL = 'BC_SHOW_WINDOW_NUMBER_MODAL';
export const BC_SHOW_DYNAMIC_CONTENT_CONTAINER = 'BC_SHOW_DYNAMIC_CONTENT_CONTAINER';
